# Generated by Django 4.0.1 on 2022-12-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isActive', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('starting_price', models.IntegerField(default=0)),
                ('current_price', models.IntegerField(default=0)),
                ('user_won', models.CharField(default=None, max_length=255)),
            ],
        ),
    ]
