# Generated by Django 4.0.1 on 2022-12-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='user_won',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
