# Generated by Django 4.0.1 on 2022-12-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_listing_user_won'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='my_listings',
            field=models.ManyToManyField(blank=True, related_name='my_listings', to='auctions.Listing'),
        ),
    ]
